theme: jekyll-theme-minimal
title: "Dive OS"
description: "An open-source operating system."
logo: "https://avatars0.githubusercontent.com/u/46858799?s=400&u=f9dc1e4e461736c099fbfdf68eabc4fa7a723b65&v=4"
show_downloads: "true"
